### PR TITLE
Extra info added to readme file

### PR DESCRIPTION
**Pull request by ezalmisa7920**
Extra info added to readme file as per requested by ezalmisa

### CODE REVIEW

**Comment by ezalmisa7920** [comment]
@ezalmisa please check the committed file

**Comment by ezalmisa** [comment]
@ezalmisa7920 good job. Please proceed to merge with master

**Comment by ezalmisa7920** [comment]
@ezalmisa ok will do. Thanks.

**Comment by ezalmisa7920** [comment]
@ezalmisa Accidentally close with merge. Reopen back the pull request

**Comment by ezalmisa** [comment]
@ezalmisa7920 no worries. Please proceed with merging now.

**Comment by ezalmisa7920** [comment]
@ezalmisa ok done merge!

**Pull request merged**
